version: "3"
services:
  reverseproxy:
      image: rajmaddy89/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-feed
        - backend-user
  backend-user:
    image: rajmaddy89/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DB_NAME: $POSTGRESS_DB_NAME
      POSTGRESS_DB_HOST: $POSTGRESS_DB_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: rajmaddy89/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DB_NAME: $POSTGRESS_DB_NAME
      POSTGRESS_DB_HOST: $POSTGRESS_DB_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: rajmaddy89/udacity-frontend:latest
    ports:
      - "8100:80"
